version: '3.4'
services:
  hass-telegram-bot:
    image: dassader/hass-telegram-bot
    restart: always
    configs:
      - source: telegram.yaml
        target: /bot/storage/telegram.yaml
    volumes:
      - hass-telegram-bot:/bot/storage
      - /mnt/data/supervisor/homeassistant:/config
    ports:
      - published: 8080
        target: 8080
        protocol: tcp
        mode: host
    deploy:
      mode: global

configs:
  telegram.yaml:
    external: true

volumes:
  hass-telegram-bot:
    external: true